### PR TITLE
Refactor how to create |FieldWriterSet| instances so that |FieldWriterSet| can be swapped with inheritance.

### PR DESCRIPTION
**Pull request by dmikurube**
@muga Can you take a look?

### CODE REVIEW

**Comment by dmikurube** [comment]
@muga Hmm, CircleCI is taking long time for some reasons... Anyway, updated again a bit.

Do we have any reason why `UnixTimestampLongFieldWriter`'s constructor was non-public?

**Comment by muga** [comment]
@dmikurube Somehow, Travis jobs not started. Just in case, I restarted them and waiting. About `UnixTimestampLongFieldWriter`, not so big reason. `public` is better for now. please change it.

**Comment by dmikurube** [comment]
Sorry, found another: `LongFieldWriter`.

**Comment by muga** [comment]
If you found others, please change them like LongFieldWriter that you fixed.

**Comment by muga** [comment]
Yes, please change them.

**Comment by muga** [comment]
Looks good. please merge it.

**Comment by dmikurube** [comment]
Thanks, merging!

**Pull request merged**
